language: java
# use older dist to install jdk8
dist: trusty
jdk:
  - openjdk11
  - oraclejdk8
# do not install anything instead return true via unix command true
install: true
script: mvn clean test
notifications:
  email:
    - github@graphhopper.com

# enable container-based stack
sudo: false
